remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

gem "github-pages", group: :jekyll_plugins

title: [RCOS Lecture Assignment 2 Site]
description: [Site For The 2nd RCOS Lecture Assignment]
